### ISSUE TITLE
Add integration with TravisCI

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-wack17s#4]
Please configure integration with TravisCI:
* [ ] [Enable repo testing in TravisCI](https://travis-ci.org/kpi-web-guild/django-girls-blog-wack17s)
* [ ] Add TravisCI badge (master branch) to `README.md` with a single commit. (click ![Build Status](https://travis-ci.org/kpi-web-guild/django-girls-blog-wack17s.svg?branch=master) next to octocat icon on [this page](https://travis-ci.org/kpi-web-guild/django-girls-blog-wack17s))
* [ ] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [ ] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.6 env and add PIP caching. Ensure you install `pre-commit` before running tests:
```yaml
language: python
python: 3.6
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files
```
* [ ] Push the branch and create a Pull Request for it.
